<Project Sdk="Microsoft.NET.Sdk">
    <!-- ... -->

    <ItemGroup>
        <!-- nuget package dependencies -->
        <PackageReference Include="PPWCode.NServiceBus.Host.I" Version="1.0.0" />
        <PackageReference Include="PPWCode.NServiceBus.Host.I.NHibernate" Version="1.0.0" />
    </ItemGroup>

    <!-- ... -->
</Project>
