<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props" />

    <ItemGroup>
        <PackageReference Include="PPWCode.Vernacular.NHibernate.IV" />

        <!-- NHibernate -->
        <PackageReference Include="NHibernate" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../I/PPWCode.NServiceBus.Host.I.csproj" />
    </ItemGroup>

</Project>
