<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props" />

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../I/PPWCode.NServiceBus.Host.I.csproj" />
    </ItemGroup>

</Project>
