name: Build & Test

on:
  push:
    branches: [ "I/next", "I/feature/*", "I/bugfix/*" ]
  pull_request:
    branches: [ "I/next" ]

jobs:
  build:
    name: Build - ${{ matrix.name-suffix }}
    runs-on: ${{ matrix.os }}
    permissions:
      checks: write
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2022]
        include:
          - os: ubuntu-latest
            name-suffix: 'Linux'
          - os: macos-latest
            name-suffix: 'macOS'
          - os: windows-2022
            name-suffix: 'Windows'

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
          global-json-file: ./global.json

      - name: Restore dependencies
        shell: bash
        run: |
          dotnet restore PPWCode.NServiceBus.Host.sln \
            --locked-mode \
            -p:Configuration=Release

      - name: Build
        shell: bash
        run: |
          dotnet build PPWCode.NServiceBus.Host.sln \
            --configuration Release \
            --no-restore \
            -p:ContinuousIntegrationBuild=true
